### ISSUE TITLE
Create config option to make item rate conversion exponential

### ISSUE THREAD

**Issue by Holmium67** [Judgy53/ConfigEgocentrism#3]
It would be cool if you could add a config option to make the rate of converting items exponential instead of linear. I.E. the more of your inventory that is egocentrism, the faster it converts. Fun little twist on egocentrism.

**Comment by Judgy53** [comment]
I've actually thought about that during development, then got sidetracked and forgot about it 😛 I should be able to implement that in next update.

**Comment by Holmium67** [comment]
BRO POG

**Comment by Holmium67** [comment]
~~update when?~~

jkjk take your time

**Comment by Judgy53** [comment]
Added in v1.2.0
